# Generated by Django 3.1.7 on 2021-03-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluguelcompra', '0001_initial'),
        ('bairros', '0001_initial'),
        ('tipoimoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('rua', models.CharField(blank=True, default=False, max_length=40, null=True)),
                ('cep', models.CharField(blank=True, default=False, max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('sqft', models.IntegerField(default=0)),
                ('garagem', models.IntegerField(default=0)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('aluguel_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aluguelcompra.aluguelcompra')),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bairros.bairro')),
                ('tipo_imovel', models.ManyToManyField(blank=True, null=True, to='tipoimoveis.TipoImovel')),
            ],
        ),
    ]
